// Generated by CoffeeScript 1.9.3
var Bullet,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Bullet = (function() {
  function Bullet(x1, y1) {
    this.x = x1;
    this.y = y1;
    this.reset = bind(this.reset, this);
    this.draw = bind(this.draw, this);
    this.set = bind(this.set, this);
    this.speed = 0;
    this.width = image_repo.bullet.width;
    this.height = image_repo.bullet.height;
  }

  Bullet.prototype.set = function(x, y, speed) {
    this.x = x;
    this.y = y;
    return this.speed = speed != null ? speed : 5;
  };

  Bullet.prototype.draw = function(cxt, bounds) {
    this.y -= this.speed;
    console.log('!! ' + this.y);
    if (this.y <= bounds[0].y - this.height) {
      console.log('end ' + this.y);
      return true;
    }
    cxt.fillStyle = "green";
    cxt.fillRect(this.x, this.y, this.width, this.height);
    return false;
  };

  Bullet.prototype.reset = function() {
    return this.x = this.y = this.speed = 0;
  };

  return Bullet;

})();
