// Generated by CoffeeScript 1.9.3
var BulletPool,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

BulletPool = (function() {
  function BulletPool(size) {
    var i, j, ref;
    this.size = size;
    this.draw = bind(this.draw, this);
    this.get = bind(this.get, this);
    this.free_pool = [];
    this.used_pool = [];
    for (i = j = 1, ref = this.size; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
      this.free_pool.push(new Bullet(0, 0));
    }
  }

  BulletPool.prototype.get = function(x, y) {
    if ((this.free_pool != null) && this.free_pool.length > 0) {
      this.free_pool[0].set(x, y);
      return this.used_pool.push(this.free_pool.shift());
    }
  };

  BulletPool.prototype.draw = function(cxt, bounds) {
    var i, results;
    i = this.used_pool.length;
    results = [];
    while (i--) {
      if (this.used_pool[i].draw(cxt, bounds)) {
        this.used_pool[i].reset();
        results.push(this.free_pool.push((this.used_pool.splice(i, 1))[0]));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  return BulletPool;

})();
