// Generated by CoffeeScript 1.9.3
var ImageRepo, image_repo;

ImageRepo = (function() {
  function ImageRepo() {
    this.bullet = {
      width: 2,
      height: 7
    };
    this.spaceship = new Image();
    this.spaceship.src = 'imgs/ship.png';
  }

  return ImageRepo;

})();

image_repo = new ImageRepo();
