// Generated by CoffeeScript 1.9.3
var Player,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Player = (function() {
  function Player(id) {
    this.id = id;
    this.gdis = bind(this.gdis, this);
    this.drawName = bind(this.drawName, this);
    this.draw = bind(this.draw, this);
    this.userUpdate = bind(this.userUpdate, this);
    this.onclick = bind(this.onclick, this);
    this.update = bind(this.update, this);
    this.x = Math.random() * 300 - 150;
    this.y = Math.random() * 300 - 150;
    this.size = 5;
    this.name = null;
    this.health = 100;
    this.level = 0;
    this.hover = false;
    this.momentum = 0;
    this.max_momentum = 3;
    this.angle = 2 * Math.PI;
    this.target_x = 0;
    this.target_y = 0;
    this.target_momentum = 0;
    this.time_since_last_avt = 0;
    this.time_since_last_ser = 0;
    this.changed = 0;
    this.bullet_pool = new BulletPool(50);
    this.shoot_cnt = 0;
  }

  Player.prototype.update = function(mouse) {
    ++this.time_since_last_ser;
    this.x += Math.cos(this.angle) * this.momentum;
    this.y += Math.sin(this.angle) * this.momentum;
    if (this.target_x !== 0 || this.target_y !== 0) {
      this.x += (this.target_x - this.x) / 20;
      this.y += (this.target_y - this.y) / 20;
    }
    if (this.gdis(this.x, this.y, mouse.worldx, mouse.worldy) < this.size + 2) {
      this.hover = true;
      return mouse.player = this;
    } else {
      return this.hover = false;
    }
  };

  Player.prototype.onclick = function(mouse) {
    if (mouse.which === 1) {
      if (mouse.ctrlKey && this.hover) {
        console.log('on click!');
      }
    } else if (mouse.which === 2) {
      mouse.preventDefault();
      return true;
    }
    return false;
  };

  Player.prototype.userUpdate = function(angle_tx, angle_ty) {
    var angle_delta, prestate;
    prestate = {
      angle: this.angle,
      momentum: this.momentum
    };
    angle_delta = Player.calAngle(this.x, this.y, angle_tx, angle_ty) - this.angle;
    angle_delta = Player.normalAngle(angle_delta);
    this.angle += angle_delta / 5;
    if (this.target_momentum !== this.momentum) {
      this.momentum += (this.target_momentum - this.momentum) / 20;
    }
    this.momentum = Math.max(this.momentum, 0);
    this.changed += Math.abs(3 * (prestate.angle - this.angle)) + this.momentum;
    if (this.changed > 1) {
      return this.time_since_last_ser = 0;
    }
  };

  Player.prototype.draw = function(cxt, bounds, b_cxt) {
    var opacity;
    opacity = Math.max(Math.min(20 / Math.max(this.time_since_last_ser - 300, 1), 1), 0.2).toFixed(3);
    if (this.hover) {
      cxt.fillStyle = 'rgba(192, 253, 247,' + opacity + ')';
    } else {
      cxt.fillStyle = 'rgba(226,219,226,' + opacity + ')';
    }
    cxt.shadowOffsetX = 0;
    cxt.shadowOffsetY = 0;
    cxt.shadowBlur = 6;
    cxt.shadowColor = 'rgba(255, 255, 255, ' + opacity * 0.7 + ')';
    cxt.beginPath();
    cxt.arc(this.x, this.y, this.size, 0, 2 * Math.PI, false);
    cxt.closePath();
    cxt.fill();
    cxt.shadowBlur = 0;
    cxt.shadowColor = '';
    this.drawName(cxt);
    return this.bullet_pool.draw(b_cxt, bounds);
  };

  Player.prototype.shoot = function() {
    return this.bullet_pool.get(this.x, this.y);
  };

  Player.prototype.drawName = function(cxt) {
    var opacity, width;
    opacity = Math.max(Math.min(20 / Math.max(this.time_since_last_ser - 300, 1), 1), 0.2).toFixed(3);
    cxt.fillStyle = 'rgba(226,219,226,' + opacity + ')';
    cxt.font = 7 + "px 'proxima-nova-1','proxima-nova-2', arial, sans-serif";
    cxt.textBaseline = 'hanging';
    width = cxt.measureText(this.name).width;
    return cxt.fillText(this.name, this.x - width / 2, this.y + 8);
  };

  Player.calAngle = function(x1, y1, x2, y2) {
    return Math.atan2(y2 - y1, x2 - x1);
  };

  Player.normalAngle = function(x) {
    while (x < -Math.PI) {
      x += 2 * Math.PI;
    }
    while (x > Math.PI) {
      x -= 2 * Math.PI;
    }
    return x;
  };

  Player.prototype.gdis = function(x1, y1, x2, y2) {
    return Math.sqrt((x1 - x2) * (x1 - x2) + (y1 - y2) * (y1 - y2));
  };

  return Player;

})();
