// Generated by CoffeeScript 1.9.3
var Scene;

Scene = (function() {
  function Scene() {
    this.users = {};
    this.user = null;
    this.camera = null;
    this.rocks = [];
  }

  return Scene;

})();
